ALLOCATOR_FIELD_CONFIG = {
    "name": {"notion_name": "Name", "type": "title"},
    "short_name": {"notion_name": "Short Name", "type": "rich_text"},
    "org_type": {"notion_name": "Org Type", "type": "select"},
    "region": {"notion_name": "Region", "type": "select"},
    "country_state": {"notion_name": "Country/State", "type": "rich_text"},
    "city": {"notion_name": "City", "type": "rich_text"},
    "domain": {"notion_name": "Domain", "type": "rich_text"},
    "main_website": {"notion_name": "Main Website", "type": "url"},
    "investments_page_url": {"notion_name": "Investments Page URL", "type": "url"},
    "latest_report_url": {"notion_name": "Latest Report URL", "type": "url"},
    "total_aum": {"notion_name": "Total AUM", "type": "number"},
    "aum_currency": {"notion_name": "AUM Currency", "type": "select"},
    "alternatives_aum": {"notion_name": "Alternatives AUM", "type": "number"},
    "check_size_low": {"notion_name": "Check Size Low", "type": "number"},
    "check_size_high": {"notion_name": "Check Size HIgh", "type": "number"},  # Note: typo in Notion
    "check_size_notes": {"notion_name": "Check Size Notes", "type": "rich_text"},
    "primary_asset_classes": {"notion_name": "Primary Asset Classes", "type": "multi_select"},
    "geographic_focus": {"notion_name": "Geographic Focus", "type": "multi_select"},
    "investment_themes": {"notion_name": "Investment Themes", "type": "multi_select"},
    "stage_preference": {"notion_name": "Stage Preference", "type": "multi_select"},
    "risk_role": {"notion_name": "Risk Role", "type": "select"},
    "emerging_manager_program": {"notion_name": "Emerging Manager Program", "type": "select"},
    "em_program_details": {"notion_name": "EM Program Details", "type": "rich_text"},
    "uses_consultants": {"notion_name": "Uses Consultants", "type": "multi_select"},
    "decision_process_summary": {"notion_name": "Decision Making Process", "type": "rich_text"},
    "research_notes": {"notion_name": "Internal Notes", "type": "rich_text"},

    # Co-Invest Fields
    "coinvest_appetite": {"notion_name": "Co-Invest Appetite", "type": "select"},
    "coinvest_program_notes": {"notion_name": "Co-Invest Program Notes", "type": "rich_text"},
    "coinvest_decision_speed": {"notion_name": "Co-Invest Decision Speed", "type": "select"},
    "requires_gp_relationship": {"notion_name": "Requires GP Relationship?", "type": "select"},
    "coinvest_preferred_sectors": {"notion_name": "Co-Invest Preferred Sectors", "type": "multi_select"},
    "coinvest_excluded_sectors": {"notion_name": "Co-Invest Excluded Sectors", "type": "multi_select"},
    "coinvest_sector_notes": {"notion_name": "Co-Invest Sector Notes", "type": "rich_text"},
    "coinvest_min_ebitda": {"notion_name": "Co-Invest Min EBITDA", "type": "number"},
    "coinvest_max_ebitda": {"notion_name": "Co-Invest Max EBITDA", "type": "number"},
    "coinvest_min_revenue": {"notion_name": "Co-Invest Min Revenue", "type": "number"},
    "coinvest_ev_range_text": {"notion_name": "Co-Invest EV Range", "type": "rich_text"},
    "coinvest_check_size_low": {"notion_name": "Co-Invest Check Size Low", "type": "number"},
    "coinvest_check_size_high": {"notion_name": "Co-Invest Check Size High", "type": "number"},
    "coinvest_check_size_notes": {"notion_name": "Co-invest Check Size Notes", "type": "rich_text"},
    "coinvest_stake_preference": {"notion_name": "Co-Invest Stake Preference", "type": "multi_select"},
    "coinvest_board_seat_requirements": {"notion_name": "Co-Invest Board Seat Requirements", "type": "select"},
    "coinvest_governance_notes": {"notion_name": "Co-Invest Governance Notes", "type": "rich_text"},
    "coinvest_deal_type_preference": {"notion_name": "Co-Invest Deal Type Preferences", "type": "multi_select"},
    "coinvest_geographic_preference": {"notion_name": "Geographic Focus", "type": "multi_select"},  # Reuses Geographic Focus
    "avoid_non_partner_led_deals": {"notion_name": "Avoid Non-Partner-Led Deals?", "type": "select"},
    "coinvest_rights_required": {"notion_name": "Co-Invest Rights Required?", "type": "select"},
    "coinvest_target_irr_range": {"notion_name": "Co-Invest Target IRR Range", "type": "rich_text"},
    "coinvest_target_moic_range": {"notion_name": "Co-Invest Target MOIC Range", "type": "number"},
    "coinvest_risk_tolerance_deal": {"notion_name": "Co-Invest Risk Tolerance (Deal-Level)", "type": "select"}
}
